# frozen_string_literal: true

# Generated by script/render-cask.py in brig-sh/brig. DO NOT EDIT.
#
# The main channel: built from the tip of main. It is not a
# release, it moves without notice, and it is not what
# `brew install --cask brig` gives you.
cask "brig@main" do
  version "0.3.1-0.20261003181354-141df7edcf71"

  on_macos do
    on_arm do
      sha256 "1cad5469e7fed3f7925bd1db438fe8fbebfb86816856003af8f485c35f5de28b"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.3.1-0.20261003181354-141df7edcf71/brig-0.3.1-0.20261003181354-141df7edcf71-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "f5c0ff080e04565732249c974b8d3b60c346c2fe500c207b197b7434f358d855"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.3.1-0.20261003181354-141df7edcf71/brig-0.3.1-0.20261003181354-141df7edcf71-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4c18851f2077cb10e011fad7d30c3edd7822b5ed27d1d8263916d76ed8087e0d"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.3.1-0.20261003181354-141df7edcf71/brig-0.3.1-0.20261003181354-141df7edcf71-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "f71e4233707dfb36f0f0d5587c5f2049a9d279083a7c3934bb1893b4f53d9326"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.3.1-0.20261003181354-141df7edcf71/brig-0.3.1-0.20261003181354-141df7edcf71-linux-amd64.tar.gz"
    end
  end

  name "brig (main)"
  desc "Run a coding agent in a microVM sandbox with only the credentials it needs"
  homepage "https://github.com/brig-sh/brig"

  livecheck do
    skip "Channel build, not a release."
  end

  conflicts_with cask: [
    "brig",
    "brig@experimental",
  ]
  depends_on cask:    [
               "brig-sh/brig/hull@main",
             ],
             formula: [
               "cosign",
             ]

  binary "brig"
  binary "brigd"
  bash_completion "completions/brig.bash"
  fish_completion "completions/brig.fish"
  zsh_completion "completions/brig.zsh"

  caveats <<~EOS
    This is the main channel, built from the tip of main.
    It is not a release: it can break, and it moves without notice.

    The supported build:  brew install --cask brig-sh/brig/brig
  EOS
end
