# This file was generated by GoReleaser. DO NOT EDIT.
cask "brig" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "dbb057ade02340adebf46339c351dd217518b994adab06e94daec8896d7ba7d6"
      url "https://github.com/brig-sh/brig/releases/download/v#{version}/brig-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "7ddbe621cdbc9c0f6850fbefe2efecba79d7b469d88cf592fc36acdc04060042"
      url "https://github.com/brig-sh/brig/releases/download/v#{version}/brig-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2a3cd2e56c9dfbc889a793af2e33c9ea1e5d27ff25ee0029e9c9773ddd1ea0d3"
      url "https://github.com/brig-sh/brig/releases/download/v#{version}/brig-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "298432246dbcd962325b9c41409fd389fd393f2dc93d5fa74fe3bd36e13ba03c"
      url "https://github.com/brig-sh/brig/releases/download/v#{version}/brig-#{version}-linux-amd64.tar.gz"
    end
  end

  name "brig"
  desc "Run a coding agent in a microVM sandbox with only the credentials it needs"
  homepage "https://github.com/brig-sh/brig"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "brig@experimental",
      "brig@main",
    ]

  depends_on cask: [
      "brig-sh/brig/hull",
    ],
    formula: [
      "cosign",
    ]

  binary "brig"
  binary "brigd"
  bash_completion "completions/brig.bash"
  fish_completion "completions/brig.fish"
  zsh_completion "completions/brig.zsh"

  # No zap stanza required

  caveats <<~EOS
    On Linux, brig drives nerdctl and needs nothing else. On macOS it drives
    hull, which brew installed alongside this cask.

    Guest images are verified with cosign before boot. An image brig-sh did
    not publish is reported and booted anyway -- bring-your-own images are a
    supported way to use brig. One that claims to be ours and fails
    verification stops and asks.

    Start with:
      brig run claude
  EOS
end
