# frozen_string_literal: true

# Generated by script/render-cask.py in brig-sh/brig. DO NOT EDIT.
#
# The main channel: built from the tip of main. It is not a
# release, it moves without notice, and it is not what
# `brew install --cask brig` gives you.
cask "brig@main" do
  version "0.3.1-0.20260930155117-82977fe602c1"

  on_macos do
    on_arm do
      sha256 "c9b814023226b0d81f66ac03d477f47ef07c664a306f7b0c035023e97190b2f6"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.3.1-0.20260930155117-82977fe602c1/brig-0.3.1-0.20260930155117-82977fe602c1-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "6bba5927a735deb859c041c0a5789a5497e981b6c3a953b1f27d1cfe3cb446da"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.3.1-0.20260930155117-82977fe602c1/brig-0.3.1-0.20260930155117-82977fe602c1-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1c76e792dde85ee5c081653e285c692f0d4d22c0ccb67d19356c87ff4771ff70"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.3.1-0.20260930155117-82977fe602c1/brig-0.3.1-0.20260930155117-82977fe602c1-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "21e5c32b074571d90bac2a3a43b1c6af93ecdd5f15957fe6fc01e1ab617f189b"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.3.1-0.20260930155117-82977fe602c1/brig-0.3.1-0.20260930155117-82977fe602c1-linux-amd64.tar.gz"
    end
  end

  name "brig (main)"
  desc "Run a coding agent in a microVM sandbox with only the credentials it needs"
  homepage "https://github.com/brig-sh/brig"

  livecheck do
    skip "Channel build, not a release."
  end

  conflicts_with cask: [
    "brig",
    "brig@experimental",
  ]
  depends_on cask:    [
               "brig-sh/brig/hull@main",
             ],
             formula: [
               "cosign",
             ]

  binary "brig"
  binary "brigd"
  bash_completion "completions/brig.bash"
  fish_completion "completions/brig.fish"
  zsh_completion "completions/brig.zsh"

  caveats <<~EOS
    This is the main channel, built from the tip of main.
    It is not a release: it can break, and it moves without notice.

    The supported build:  brew install --cask brig-sh/brig/brig
  EOS
end
