# frozen_string_literal: true

# Generated by script/render-cask.py in brig-sh/brig. DO NOT EDIT.
#
# The main channel: built from the tip of main. It is not a
# release, it moves without notice, and it is not what
# `brew install --cask brig` gives you.
cask "brig@main" do
  version "0.2.1-0.20260925224810-02792b74dc98"

  on_macos do
    on_arm do
      sha256 "8adab2a8f6ca6f6009047cf8a3628b6f3452bba91b6bda0a70634edc594ee245"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.2.1-0.20260925224810-02792b74dc98/brig-0.2.1-0.20260925224810-02792b74dc98-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "846936a6537d03dee08e1acda68dedc8270f1e3c5aa385f920fed3c35b738665"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.2.1-0.20260925224810-02792b74dc98/brig-0.2.1-0.20260925224810-02792b74dc98-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d6ab1ba16ab9d47c856d2fc23c3edb25a72abd4e21201be735a49869201c5a2d"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.2.1-0.20260925224810-02792b74dc98/brig-0.2.1-0.20260925224810-02792b74dc98-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "abdafe2676ecfc8f3fc6562bf88a7b0e08c7f007e61aba37e7fb5588591bde15"
      url "https://github.com/brig-sh/brig/releases/download/channel-main-0.2.1-0.20260925224810-02792b74dc98/brig-0.2.1-0.20260925224810-02792b74dc98-linux-amd64.tar.gz"
    end
  end

  name "brig (main)"
  desc "Run a coding agent in a microVM sandbox with only the credentials it needs"
  homepage "https://github.com/brig-sh/brig"

  livecheck do
    skip "Channel build, not a release."
  end

  conflicts_with cask: [
    "brig",
    "brig@experimental",
  ]
  depends_on cask:    [
               "brig-sh/brig/hull@main",
             ],
             formula: [
               "cosign",
             ]

  binary "brig"
  binary "brigd"
  bash_completion "completions/brig.bash"
  fish_completion "completions/brig.fish"
  zsh_completion "completions/brig.zsh"

  caveats <<~EOS
    This is the main channel, built from the tip of main.
    It is not a release: it can break, and it moves without notice.

    The supported build:  brew install --cask brig-sh/brig/brig
  EOS
end
