# frozen_string_literal: true

# Generated by scripts/render-cask.py in brig-sh/hull. DO NOT EDIT.
#
# The main channel: built from the tip of main. It is not a
# release, it moves without notice, and it is not what
# `brew install --cask hull` gives you.
cask "hull@main" do
  version "0.1.0-rc30-main.20261006114751.2d6a20d"
  sha256 "ded437fd3c24bf305da2f074b485f567ea0fe5875566c0b9b07c77fae7e818d1"

  url "https://github.com/brig-sh/hull/releases/download/channel-main-#{version}/hull-#{version}-arm64.tar.gz"
  name "hull (main)"
  desc "Run unikernels and sandboxed Linux containers as microVMs on Apple Silicon"
  homepage "https://github.com/brig-sh/hull"

  livecheck do
    skip "Channel build, not a release."
  end

  conflicts_with cask: [
    "hull",
    "hull@experimental",
  ]
  depends_on arch:    :arm64,
             formula: [
               "cosign",
             ]
  depends_on :macos

  binary "hull"
  binary "vz-runner"
  binary "hvi"

  caveats <<~EOS
    This is the main channel, built from the tip of main.
    It is not a release: it can break, and it moves without notice.

    The supported build:  brew install --cask brig-sh/brig/hull
  EOS
end
