# frozen_string_literal: true

# Generated by scripts/render-cask.py in brig-sh/hull. DO NOT EDIT.
#
# The experimental channel: built from feat/overlay-block-rootfs. It is not a
# release, it moves without notice, and it is not what
# `brew install --cask hull` gives you.
cask "hull@experimental" do
  version "0.1.0-rc31-experimental.20261009132127.320a0a8"
  sha256 "fb8c40b943ebe59a9163c9f1eb1c0bc12a17855b79026076796f963d55ab05d1"

  url "https://github.com/brig-sh/hull/releases/download/channel-experimental-#{version}/hull-#{version}-arm64.tar.gz"
  name "hull (experimental)"
  desc "Run unikernels and sandboxed Linux containers as microVMs on Apple Silicon"
  homepage "https://github.com/brig-sh/hull"

  livecheck do
    skip "Channel build, not a release."
  end

  conflicts_with cask: [
    "hull",
    "hull@main",
  ]
  depends_on arch:    :arm64,
             formula: [
               "cosign",
             ]
  depends_on :macos

  binary "hull"
  binary "vz-runner"
  binary "hvi"

  caveats <<~EOS
    This is the experimental channel, built from feat/overlay-block-rootfs.
    It is not a release: it can break, and it moves without notice.

    The supported build:  brew install --cask brig-sh/brig/hull
  EOS
end
